%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.2 and Fixed-Point Designer 5.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function out1 = fun1Ibr_wrapper_fixpt(V_n,G_br,coeftr,Ih,Node_P,Node_N,Node_P_tp,Node_N_tp)
    fm = get_fimath();
    V_n_in = fi( V_n, 1, 32, 17, fm );
    G_br_in = fi( G_br, 1, 32, 17, fm );
    coeftr_in = fi( coeftr, 1, 32, 17, fm );
    Ih_in = fi( Ih, 1, 32, 17, fm );
    Node_P_in = fi( Node_P, 1, 3, 0, fm );
    Node_N_in = fi( Node_N, 1, 2, 0, fm );
    Node_P_tp_in = fi( Node_P_tp, 1, 4, 0, fm );
    Node_N_tp_in = fi( Node_N_tp, 1, 2, 0, fm );
    [out1_out] = fun1Ibr_fixpt( V_n_in, G_br_in, coeftr_in, Ih_in, Node_P_in, Node_N_in, Node_P_tp_in, Node_N_tp_in );
    out1 = double( out1_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
