%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.2 and Fixed-Point Designer 5.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ I_history ] = fun1Ihistory_fixpt(I_history_1,I_source,Node_P,Node_N)
    % Normal branches
    fm = get_fimath();
    I_history = fi(I_history_1, 1, 34, 19, fm);

    if  Node_P ~= fi(0, 1, 2, 0, fm) && Node_N ~= fi(0, 1, 2, 0, fm)
        I_history(Node_N) = fi(I_history(Node_N) + I_source, 1, 34, 19, fm); 
        I_history(Node_P) = I_history(Node_P) - I_source; 
    else
        if Node_N ~= fi(0, 1, 2, 0, fm) 
            I_history(Node_N) = fi(I_history(Node_N) + I_source, 1, 34, 19, fm);
        elseif Node_P ~= fi(0, 1, 2, 0, fm) 
            I_history(Node_P) = fi(I_history(Node_P) - I_source, 1, 34, 19, fm);  
        end 
    end

end



function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end


function y = fi_uminus(a)
    coder.inline( 'always' );
    if isfi( a )
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = -fi( a, new_nt, fimath( a ) );
    else
        y = -a;
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
