%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.2 and Fixed-Point Designer 5.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function out1 = fun2Ihs_wrapper_fixpt(V_n,I_br,coef1,coef2,Node_P,Node_N)
    fm = get_fimath();
    V_n_in = fi( V_n, 1, 34, 19, fm );
    I_br_in = fi( I_br, 1, 34, 19, fm );
    coef1_in = fi( coef1, 1, 34, 19, fm );
    coef2_in = fi( coef2, 1, 34, 19, fm );
    Node_P_in = fi( Node_P, 1, 4, 0, fm );
    Node_N_in = fi( Node_N, 1, 4, 0, fm );
    [out1_out] = fun2Ihs_fixpt( V_n_in, I_br_in, coef1_in, coef2_in, Node_P_in, Node_N_in );
    out1 = double( out1_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
