%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.2 and Fixed-Point Designer 5.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function A = Vnodal_wrapper_fixpt(I_history,I_U,G,G_UU,G_UK,Vk,flag)
    fm = get_fimath();
    I_history_in = fi( I_history, 1, 34, 19, fm );
    I_U_in = I_U;
    G_in = fi( G, 1, 34, 19, fm );
    G_UU_in = G_UU;
    G_UK_in = G_UK;
    Vk_in = fi( Vk, 1, 2, 0, fm );
    flag_in = fi( flag, 1, 2, 0, fm );
    [A_out] = Vnodal_fixpt( I_history_in, I_U_in, G_in, G_UU_in, G_UK_in, Vk_in, flag_in );
    A = double( A_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
